#!/bin/bash

TOP=`dirname $0`
TOP=`cd $TOP/.. && pwd`

JAR=`ls $TOP/target/*.jar`

test -z "$1" && {
  echo "Usage : rocktest <scenario.yaml>"
  exit 1
}

test -r "$1" || {
    echo "Cannot access file $1"
    exit 1
}

java -Duser.timezone=GMT -jar $JAR "$1" -Doracle.jdbc.timezoneAsRegion=false

