#!/bin/bash

TOP=$(cd $(dirname $0)/.. && pwd)

NB=$(ls $TOP/target/*.jar | wc -l)

test $NB == 1 || {
  echo "Error: found $NB jars in target, expected 1"
  exit 1
}

JAR=$(ls $TOP/target/*.jar)


echo $OS | grep -i windows && {
  TOPWIN=$(cygpath -w $TOP)
  JARWIN=$(cygpath -w $JAR)
  SEP=";"
} || {
  TOPWIN=$TOP
  JARWIN=$JAR
  SEP=":"
}


test -z "$1" && {
  echo "Usage : rocktest <scenario.yaml>"
  exit 1
}

test -r "$1" || {
    echo "Cannot access file $1"
    exit 1
}

java -cp "${ROCKLIB}/*${SEP}${JARWIN}${SEP}${TOPWIN}/lib/*${SEP}${TOPWIN}/target/dependencies/*" io.rocktest.RocktestApplication "$1"
