#!/bin/bash

TOP=$(cd $(dirname $0)/.. && pwd)

NB=$(ls $TOP/target/*.jar | wc -l)

test $NB == 1 || {
  echo "Error: found $NB jars in target, expected 1"
  exit 1
}

JAR=$(ls $TOP/target/*.jar)

test -z "$1" && {
  echo "Usage : rocktest <scenario.yaml>"
  exit 1
}

test -r "$1" || {
    echo "Cannot access file $1"
    exit 1
}

java -Duser.timezone=GMT -jar $JAR "$1" -Doracle.jdbc.timezoneAsRegion=false

