#!/bin/bash

TOP=$(dirname "$0")

test -z "$1" && {
  echo "Usage : rockall <directory>"
  exit 1
}

test -d "$1" || {
    echo "Cannot access directory $1"
    exit 1
}


for F in $(ls $1/*.yaml) ; do
  printf "%s - " `basename $F`

  $TOP/rocktest $F
  
  test $? = 130 && {
      echo
      exit 130
  }

done
